name: SonarQube Analysis

on:
  push:
    branches:
      - main

  pull_request:
    branches:
      - main
      - master

jobs:
  sonar:
    name: Analyze
    runs-on: ubuntu-latest

    steps:
      # Checkout source code
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      # Setup Node.js
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 22
          cache: npm

      # Install dependencies
      - name: Install dependencies
        run: npm ci

      # Build project (only if build script exists)
      - name: Build
        run: npm run build --if-present

      # SonarQube Cloud Scan
      - name: SonarQube Scan
        uses: SonarSource/sonarqube-scan-action@v5
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
        with:
          args: >
            -Dsonar.organization=abhipnm
            -Dsonar.projectKey=quiz-time
            -Dsonar.host.url=https://sonarcloud.io
